### ISSUE TITLE
i have a problem about copulae.txt

### ISSUE THREAD

**Issue by salmon002** [vinodhkris/SarcasmDetector#3]
how to get this file? thx

**Comment by vinodhkris** [comment]
It is a list of copular verbs. You can get it from https://www.wikipedia.org/en/List_of_English_copulae .

**Comment by salmon002** [comment]
thank you, i got it.
however i also have a problem. we project not contain trigram_rules.txt file. 
could you please tell me what content this file contains.
thank you

**Comment by vinodhkris** [comment]
From the paper (http://www.cs.utah.edu/~huangrh/official-sarcasm-cameraReady-v2.pdf) page 5:

> The 20 POS trigram patterns are similar in nature
and are designed to capture seven general types of
verb phrases: verb and adverb mixtures, an infinitive
VP that includes an adverb, a verb phrase followed
by a noun phrase, a verb phrase followed by a
prepositional phrase, a verb followed by an adjective
phrase, or an infinitive VP followed by an adjective,
noun, or pronoun

**Comment by salmon002** [comment]
yes, thank you, i read the paper, but my result is error!
`V + R + R
R + V + R
R + R + V
V + V + R
V + R + V
R + V + V
TO + V + R
TO + R + V
V + N + N
V + V + N
V + V + P
V + P + P
V + A + A
TO + R + A
TO + R + N
TO + R + O`
but the result is less than 20, and is there a problem?

**Comment by vinodhkris** [comment]
Hey, I've attached the file I used for this. I'll update the repository as well. Thanks

[trigram_rules.txt](https://github.com/vinodhkris/SarcasmDetector/files/588196/trigram_rules.txt)

**Comment by salmon002** [comment]
thanks a lot.
