### ISSUE TITLE
i have problem about this project

### ISSUE THREAD

**Issue by salmon002** [vinodhkris/SarcasmDetector#4]
i am happy to read this code, but i found a problem.
for example: 
@PlayStation and add an extra bit of strain to PSN,  causing it to go down for a couple of hours.  #sarcasm
the result of pos tag is:
@PlayStation and add an extra bit of strain to PSN , causing it to go down for a couple of hours . #sarcasm
but in this code, we use line.split(), the result is:
@PlayStation and add an extra bit of strain to PSN,  causing it to go down for a couple of hours.  #sarcasm
if i want to find tag of 'causing' word,  the index of line.split() is 10, 
i will see posTags[lineNum][10] as this word posTag. In fact, its posTag is posTags[lineNum][11].

**Comment by vinodhkris** [comment]
is ',' the problem? If it is, I think you can use strip to remove all punctuations and then apply the pos tagger. In any case, feel free to correct the code and send the pull request, I'll check it and patch it. Thanks!
