### ISSUE TITLE
i have some questions about this code

### ISSUE THREAD

**Issue by salmon002** [vinodhkris/SarcasmDetector#5]
i am very happy to read your code. but i have three question when reading this code. 
1. i do not know content of `trigram_rules.txt`. Cloud you tell me directly ?
2. in extractPredicates function, 
is code `if (posTags[num][pos] == "R" and posTags[num][pos] == "A" and posTags[num][pos] == "N") or (posTags[num][pos] == "D" and posTags[num][pos] == "A" and posTags[num][pos] == "N")` correct ?
i think it should be convert to 
`if (posTags[num][pos] == "R" and posTags[num][pos+1] == "A" and posTags[num][pos+2] == "N") or (posTags[num][pos] == "D" and posTags[num][pos+1] == "A" and posTags[num][pos+2] == "N")`
3. in calculateScorePredicates function
   is `numofgrams = len(phrase.split())` correct ?
   i think numofgrams should be negative word, but it is predicate word.

I learned a lot from your code, 
for these problems, i hope to get your answer.
thx

**Comment by vinodhkris** [comment]
Hey, Please find the answers below : 

1. I have attached it in the reply of the other issue. Please check that out.
2. Changed and updated code
3. It seems correct, the method actually gets negative predicates. What do you think it should be replaced by?

Thanks

**Comment by salmon002** [comment]
for third question:
`def calculateScorePredicates(negwords, phrase, posFile, negFile):
	numofgrams = len(phrase.split())
	negwordslist = list(negwords)
	countpos = 0
	countneg = 0
	for line in posFile:
		for word in negwordslist:
			pos = extractWordPos(word,line.strip(),0)
			pos1 = extractWordPos(phrase,line.strip(),0)
			if pos!=-1 and pos1!=-1:
				pos+=1
				pos1+=1
				pos1end = pos1+numofgrams 
				try:
					if abs(pos - pos1) <=5 or abs(pos - pos1end)<=5:`

`numofgrams` is different from 
`def extractPredicates(negative_seed_word, inputFile)	:
	copulae = open("copulae.txt","r")
	copularVerbs = list()
	unigram = list()
	bigram = list()
	trigram = list()
	num = 0
	for lines in copulae:
		copularVerbs.append(lines)
	for line in inputFile:
		for word in copularVerbs:
			pos = extractWordPosPredicate(word.strip(),line.strip(),1)			#added inflections here; pointer points to the location right after the copular verb
			if pos!=-1:														#Copular verb found
				pos1 = extractWordPos(negative_seed_word,line.strip(),0)		#see if the negative word is there
				if pos1!=-1:
					pos1+=1  												#the pointer now points to the negative word
					numofgram = len(negative_seed_word.split())
					pos1end = pos1+numofgram   								#the pointer points to the end of then negative word
					if abs(pos - pos1) <=5 or abs(pos - pos1end)<=5:`

**Comment by vinodhkris** [comment]
The First one is for predicates, whereas the second one just involves the seed words. So they don't exactly stand for the same thing. Either way, send me a pull request if you feel the need for change and I can run it and accept it if it seems ok. 

Thanks

**Comment by salmon002** [comment]
ok, i got it, thank you.
